version: '3'

services:
  postgres:
    image: postgres:15
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data
    expose:
      - 5432

  knowledg:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ENTITY_DIR=src/entities/*.entity.*
    working_dir: /app
    volumes:
      - .:/app